blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://nebulascloud.atlassian.net/wiki/spaces/SA/pages/32636931/Workflow+Planning+Institute #change to WPI once Confluence is setup
    about: Please check the project documentation for answers to common questions.